device: cpu

train:
  n_iters: 1000
  frames_per_batch: 4096  # for each iteration
  total_frames: 4_096_000  # n_iters * frames_per_batch
  n_epochs: 8
  minibatch_size: 512  # how many frame used for each update step

optim:
  lr: 3.0e-4
  max_grad_norm: 1.0
  loss_eps: 0.99

sac:
  centralized_qvalue: true  # IPPO if false, MAPPO if true

arch:
  depth: 2
  num_cells: 64
