device: cpu

train:
  n_iters: 10
  frames_per_batch: 1024  # for each iteration
  total_frames: 10240  # n_iters * frames_per_batch
  n_epochs: 8
  minibatch_size: 512  # how many frame used for each update step

optim:
  lr: 3.0e-4
  max_grad_norm: 1.0

ppo:
  clip_epsilon: 0.2   # clip value for ppo loss
  gamma: 0.99  # discount factor
  lmbda: 0.90  # lambda for GAE
  entropy_eps:  1.0e-4  # coefficient of the entropy term
  share_parameters_policy: false  # homogenous policy when true
  share_parameters_critic: false  # homogenous cirtic when true
  centralized_critic: true  # IPPO if false, MAPPO if true

arch:
  depth: 2
  num_cells: 64
  # activation: "tanh"  # or relu